---
title: "Optim Examples"
author: "Jean Dos Santos"
date: "28/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





```{r}
## "wild" function , global minimum at about -15.81515
fw <- function (x, y){
  y + 10*sin(0.3*x*y)*sin(1.3*x^2) + 0.00001*x^4 + 0.2*x+80*y
}

res <- optim(par = c(10,10), fn = function(x) fw(x[1], x[2]), lower=c(-100,-100), upper=c(100,100), method = "L-BFGS-B")
res
```



```{r}
loss <- function(x){
  x1 <- x[1]
  x2 <- x[2]
  
  y <- x1^2 + x2^3
  
  y
  
}

optim(par=c(100, 100), fn = loss, lower= c(-100, -100), upper = c(100,100))
```


```{r}
xx=c(1,2,3,4,5)
zz=c(3,4,2,2,1)
yy=c(30,40,22,33,40)

funk=function(param,x,y,z){
  
  a=rep(param[1],5)
  b=param[2]
  d=param[3]
  
  fit=sum((y-(a+b*x+z*d))^2)
  return(fit)
}

optim(par=c(1,1,1), fn=funk, x=xx, y=yy, z=zz) 
```



```{r}
### sphere-DEoptim.R file ###
library(DEoptim) # load DEoptim
sphere=function(x) sum(x^2)
D=5
maxit=100
set.seed(12345) # set for replicability

C=DEoptim.control(strategy=1,NP=5,itermax=maxit,CR=0.9, trace=25,storepopfrom=1,storepopfreq=1)

# perform the optimization:
D=suppressWarnings(DEoptim(sphere,rep(-5.2,D),rep(5.2,D),control=C))
# show result:
summary(D)
# plot(D, plot.type="storepop")
```


```{r}
dat=data.frame(x=c(1,2,3,4,5,6), 
               y=c(1,3,5,6,8,12),
               z=2*c(1,2,3,7,8,10))
               
min.RSS <- function(data, par) {
              with(data, sum((par[1]+par[2]*x - y)^2))
}

result <- optim(par = c(0, 1), min.RSS, data = dat)
# I find the optimised parameters in result$par
# the minimised RSS is stored in result$value
result
```

